name: update json data
on:
  # push:
  #   paths:
  #     - '.github/workflows/update_data.yml'
  # pull_request:
  #   paths:
  #     - '.github/workflows/update_data.yml'
  schedule:
    - cron:  '20 11 * * *'
  repository_dispatch:
    types: [update_data]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout covid19
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Checkout covid19-scraping
      uses: actions/checkout@v2
      with:
        repository: stop-covid19-hyogo/covid19-scraping
        ref: 'gh-pages'
        path: 'covid19-scraping'

    - name: copy files
      run: |
        cp -p covid19-scraping/*.json data
        rm data/open_data_warnings.json
        rm -rf covid19-scraping

    - run: git diff

    - name: Commit files
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data
        git commit -m "update json data `date '+%Y-%m-%dT%H:%M:%SZ'`"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
        labels: auto_merge
        branch-suffix: 'short-commit-hash'

    - name : Wait for Pull Request Marge
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Re checkout development
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Create GitHub release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: patch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

    - name: Trigger of Production Deploy
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: production_deploy
